# Generated by Django 4.0.1 on 2022-02-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='notesMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('selectfile', models.FileField(upload_to='NotesFolder')),
                ('comments', models.TextField()),
            ],
        ),
    ]
